### PR TITLE
feat: add angelogalav notes

### PR DESCRIPTION
**Pull request by Flecart**

### CODE REVIEW

**Comment by foxyseta** [comment]
As explained here https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/ (we should really translate this https://github.com/csunibo/csunibo.github.io/issues/24), you can just rename `Images/` to `images/`.

**Comment by Flecart** [comment]
@foxyseta renaming the folder is not enough. 
The wiki says if a folder passes the check, in this case "angelogalav", it shouldn´t  check the subfolders, but it doesn't seem to happen.

**Comment by foxyseta** [comment]
(The conditioned mentioned is stated in https://csunibo.github.io/wiki/raccolte-di-risorse/controlli-automatici/)

As stated by the wiki page, that condition only applies to `dispense/`, `lucidi/`, `prove/`.

**Comment by foxyseta** [comment]
If this is too much work, I can also chip in using `stdrename` or `csurename` on my own.

**Comment by Flecart** [comment]
yeah foxy there are too many images, even if you use csurename I think you have to update the markdown links manually, I hope I'm wrong.

I counted that there are 106 images with low underscore, assuming you need ~20 secs to find the file(s) that link to the image, the reference within the file, and fix the link manually, you would need about half an hour of non stop renaming.

**Comment by foxyseta** [comment]
This wasn't that bad, since most images filenames were using snake_case anyway. But we do neet to find something (maybe `sed`?) to quickly fix references in files.

**Pull request merged**
